# This GitHub Actions workflow builds a Capacitor Android App (APK).
#
# Key Improvements in this version:
# 1. Gradle Caching: Added caching for Gradle dependencies to significantly speed up build times on subsequent runs.
# 2. Better Release Strategy: The workflow now creates a GitHub Release only when you push a version tag (e.g., "v1.0.1"), which is standard practice.
# 3. Updated Actions: Uses the latest versions of actions like `softprops/action-gh-release@v2`.
# 4. Streamlined Steps: Consolidated and clarified steps for better readability and efficiency.

name: Build Android APK

on:
  push:
    branches: [ main, develop ]
    # The release process is now triggered by pushing a version tag.
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Caching Gradle dependencies to speed up subsequent builds.
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Node.js dependencies
        run: npm install

      - name: Build web assets
        run: npm run build:mobile

      - name: Initialize Capacitor Android platform
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          else
            echo "Android platform already exists."
          fi

      # This step helps ensure older projects are configured correctly for Java 21.
      - name: Configure Gradle for Java 21
        run: |
          # Point gradle.properties to the correct Java home if not already set.
          if ! grep -q "org.gradle.java.home" android/gradle.properties; then
            echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties
          fi

      - name: Sync Capacitor project
        run: npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      # This step runs only when a new version tag is pushed to the repository.
      - name: Create GitHub Release and Upload APK
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          # This automatically generates release notes from your commit messages.
          generate_release_notes: true
          files: android/app/build/outputs/apk/debug/app-debug.apk

