name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v2.3.4

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Package (Linux)
        run: npm run package:linux

      - name: Zip linux-unpacked
        run: |
          cd dist
          zip -r linux-unpacked.zip linux-unpacked

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/linux-unpacked.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Package (Windows)
        run: npm run package:win

      - name: Zip win-unpacked
        run: |
          cd dist
          powershell Compress-Archive -Path win-unpacked -DestinationPath win-unpacked.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/win-unpacked.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: dist

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/linux-unpacked.zip
            dist/win-unpacked.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
