name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v2.3.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32

      
      - name: Install dependencies
        run: npm install

      - name: Build and Package
        run: npm run package

      - name: Zip linux-unpacked
        run: |
          cd dist
          zip -r linux-unpacked.zip linux-unpacked

      - name: Zip win-unpacked
        run: |
          cd dist
          zip -r win-unpacked.zip win-unpacked

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/linux-unpacked.zip
            dist/win-unpacked.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
